#!/usr/bin/env bash
curl -sL https://deb.nodesource.com/setup_14.x -o /tmp/nodesource_setup.sh
sudo bash /tmp/nodesource_setup.sh
sudo rm -rf /tmp/nodesource_setup.sh
sudo apt-get -y install nodejs build-essential
sudo npm install -g npm

