#!/usr/bin/env bash
mkdir -pv /platform/sites/$1
setfacl -R -d -m u:denadmin:rwx /platform/sites/$1
setfacl -R -m u:denadmin:rwx /platform/sites/$1
setfacl -R -d -m g:denplatform:rwx /platform/sites/$1
setfacl -R -m g:denplatform:rwx /platform/sites/$1

