#!/usr/bin/env bash
if [ -d /etc/nginx/sites-available ]; then
  cd /etc/nginx/sites-available
  sudo touch $1
  cat << NGINX_FILE > $1
server {
        listen 80;
        listen [::]:80;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name $1;

        location / {
            proxy_pass http://localhost:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade \$http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host \$host;
            proxy_cache_bypass \$http_upgrade;
        }
}
NGINX_FILE
sudo ln -s /etc/nginx/sites-available/$1 /etc/nginx/sites-enabled/
sudo nginx -t

fi
